# =============================
# データベース設定
# =============================
spring.datasource.url=jdbc:postgresql://dpg-d8v11e7avr4c73frsgeg-a:5432/demo_db_6wzy
spring.datasource.username=demo_db
spring.datasource.password=f43xyElfuEmnjmG02fJeWjWaUfN2hVFU
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================
# JPA / Hibernate 設定
# =============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =============================
# Thymeleaf 設定
# =============================
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# =============================
# サーバー設定
# =============================
server.port=${PORT:8080}
